quarkus.http.port=8081
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=nJemone.0999
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/jets


quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true

quarkus.oidc.auth-server-url=http://localhost:8082/realms/jets_quarcus
#quarkus.http.auth.permission.authenticated.paths=/*
#quarkus.http.auth.permission.authenticated.policy=authenticated
#quarkus.oidc.roles.role-claim-path=realm_access/roles


quarkus.rest-client.ip-api.url=https://api.ipify.org
quarkus.rest-client.time-api.url=https://timeapi.io
quarkus.oidc.enabled=false
// samo da se izbjegne keyclock radi testiranja
quarkus.http.auth.permission.permit-all.paths=/*
quarkus.http.auth.permission.permit-all.policy=permit

