quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=nJemone.0999
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/jets

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true